brew_taps:
  - domt4/autoupdate
  - frdmn/formulas
  - homebrew/cask-versions
  - homebrew/cask-fonts

brew_packages:
  - ansible
  - asciinema
  - bat
  - bitwarden-cli
  - composer
  - coreutils
  - ddig
  - dev-search
  - exa
  - exiftool
  - ffmpeg
  - git-extras
  - go
  - gpg2
  - htop
  - imapsync
  - iperf
  - jq
  - mas
  - media-info
  - mitmproxy
  - mtr
  - nmap
  - nodejs
  - odig
  - pinentry-mac
  - ruby
  - telnet
  - terminal-notifier
  - tmux
  - uping
  - wget
  - youtube-dlc
  - zplug
  - zsh

cask_packages:
  - 1password
  - aerial
  - alfred
  - appcleaner
  - atext
  - bartender
  - bitwarden
  - carbon-copy-cloner
  - discord
  - docker
  - dropbox
  - dropshare
  - font-hack-nerd-font
  - gas-mask
  - gitup
  - google-chrome
  - hex-fiend
  - iterm2
  - keka
  - nordvpn
  - nvalt
  - spotify
  - telegram
  - textual
  - transmit
  - vagrant
#  - virtualbox
  - visual-studio-code
  - vlc
  - wireshark

cask_ql_packages:
  - qlmarkdown
  - qlstephen
  - quicklook-json
  - suspicious-package
