- name: "[docker] Prune unused containers older >24h"
  community.docker.docker_prune:
    containers: yes
    containers_filters:
      until: 24h

- name: "[docker] Prune unused images"
  community.docker.docker_prune:
    images: yes

- name: "[docker] Prune unused networks"
  community.docker.docker_prune:
    networks: yes

- name: "[docker] Prune unused volumes"
  community.docker.docker_prune:
    volumes: yes

- name: "[docker] Prune builder cache"
  community.docker.docker_prune:
    builder_cache: yes
  